# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('f0aa8e61-06cd-4577-9da9-c41a4c9fff7c'), editable=False, verbose_name='商品唯一ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名字')),
                ('price', models.IntegerField(verbose_name='商品价格')),
                ('category', models.SmallIntegerField(choices=[(11, '实物商品'), (12, '虚拟商品')], default=11, verbose_name='商品种类')),
            ],
            options={
                'db_table': 'mall_product',
            },
        ),
    ]
