# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('989b9d78-a002-4a82-a5c6-bd70b0f2ae61'), editable=False, verbose_name='商品唯一ID'),
        ),
    ]
