# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mall', '0002_auto_20200327_2226'),
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='购买数量')),
                ('amount', models.FloatField(verbose_name='总额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='购买日期')),
                ('status', models.SmallIntegerField(choices=[(10, '购物车'), (11, '已经生成订单'), (12, '已经付款'), (13, '已经发货'), (14, '已经收货'), (15, '已经删除')], default=10, verbose_name='状态')),
            ],
            options={
                'db_table': 'mine_cart',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(10, '购物车'), (11, '已经生成订单'), (12, '已经付款'), (13, '已经发货'), (14, '已经收货'), (15, '已经删除')], default=11, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.User'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('user_id', 'product', 'order')]),
        ),
    ]
